# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/

stages:
  - deploy

variables:
  NODE_VERSION: "18.12.1"
  PHP_VERSION: "8.2"

deploy-job:
  stage: deploy
  image: alpine:latest
  before_script:
    - "command -v ssh-agent >/dev/null || ( apk add --update openssh )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SSH_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$SSH_IP "
      cd /home/ewilan/www/$CI_PROJECT_NAME &&
      git pull &&
      /usr/bin/php$PHP_VERSION /usr/local/bin/composer install &&
      php$PHP_VERSION artisan optimize:clear &&
      /usr/bin/php$PHP_VERSION /usr/local/bin/composer i --no-dev &&
      php$PHP_VERSION artisan setup:clean &&
      php$PHP_VERSION artisan scout:fresh &&
      /home/ewilan/.nvm/versions/node/v$NODE_VERSION/bin/pnpm i &&
      /home/ewilan/.nvm/versions/node/v$NODE_VERSION/bin/pnpm build &&
      supervisorctl restart fictions-octane-worker:fictions-octane-worker_00 &&
      discord-queerotronic.sh '$CI_PROJECT_TITLE'"
  only:
    - main
