# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/

stages:
  - deploy

variables:
  NODE_VERSION: "18.12.1"
  PHP_VERSION: "8.2"

deploy-job:
  stage: deploy
  image: ewilanriviere/laravel-docker
  services:
    - mysql:8.0
  script:
    - git clone https://gitlab.com/ewilan-riviere/glamdring.git
    - cd glamdring
    - composer install
  only:
    - main
