# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/

stages:
  - test

variables:
  NODE_VERSION: "18.12.1"
  PHP_VERSION: "8.2"

test-job:
  stage: test
  image: php:8.2-cli
  script:
    - git clone https://gitlab.com/ewilan-riviere/glamdring.git
    - cd glamdring
    - php -v
    - composer install
  only:
    - main
