// This file is auto generated by TypescriptableLaravel.
const Routes: Record<App.Route.Name, App.Route.Entity> = {
  'login': {
    name: 'login',
    path: '/login',
    params: undefined,
    method: 'POST',
  },
  'logout': {
    name: 'logout',
    path: '/logout',
    params: undefined,
    method: 'POST',
  },
  'password.email': {
    name: 'password.email',
    path: '/forgot-password',
    params: undefined,
    method: 'POST',
  },
  'password.reset': {
    name: 'password.reset',
    path: '/reset-password/{token}',
    params: {
      token: 'string',
    },
    method: 'GET',
  },
  'password.update': {
    name: 'password.update',
    path: '/reset-password',
    params: undefined,
    method: 'POST',
  },
  'register': {
    name: 'register',
    path: '/register',
    params: undefined,
    method: 'POST',
  },
  'user-profile-information.update': {
    name: 'user-profile-information.update',
    path: '/user/profile-information',
    params: undefined,
    method: 'PUT',
  },
  'user-password.update': {
    name: 'user-password.update',
    path: '/user/password',
    params: undefined,
    method: 'PUT',
  },
  'password.confirm': {
    name: 'password.confirm',
    path: '/user/confirm-password',
    params: undefined,
    method: 'POST',
  },
  'password.confirmation': {
    name: 'password.confirmation',
    path: '/user/confirmed-password-status',
    params: undefined,
    method: 'GET',
  },
  'two-factor-challenge': {
    name: 'two-factor-challenge',
    path: '/two-factor-challenge',
    params: undefined,
    method: 'POST',
  },
  'two-factor.disable': {
    name: 'two-factor.disable',
    path: '/user/two-factor-authentication',
    params: undefined,
    method: 'DELETE',
  },
  'two-factor.confirm': {
    name: 'two-factor.confirm',
    path: '/user/confirmed-two-factor-authentication',
    params: undefined,
    method: 'POST',
  },
  'two-factor.qr-code': {
    name: 'two-factor.qr-code',
    path: '/user/two-factor-qr-code',
    params: undefined,
    method: 'GET',
  },
  'two-factor.secret-key': {
    name: 'two-factor.secret-key',
    path: '/user/two-factor-secret-key',
    params: undefined,
    method: 'GET',
  },
  'user/two-factor-recovery-codes': {
    name: 'user/two-factor-recovery-codes',
    path: '/user/two-factor-recovery-codes',
    params: undefined,
    method: 'POST',
  },
  'profile.show': {
    name: 'profile.show',
    path: '/user/profile',
    params: undefined,
    method: 'GET',
  },
  'other-browser-sessions.destroy': {
    name: 'other-browser-sessions.destroy',
    path: '/user/other-browser-sessions',
    params: undefined,
    method: 'DELETE',
  },
  'current-user-photo.destroy': {
    name: 'current-user-photo.destroy',
    path: '/user/profile-photo',
    params: undefined,
    method: 'DELETE',
  },
  'current-user.destroy': {
    name: 'current-user.destroy',
    path: '/user',
    params: undefined,
    method: 'DELETE',
  },
  'sanctum.csrf-cookie': {
    name: 'sanctum.csrf-cookie',
    path: '/sanctum/csrf-cookie',
    params: undefined,
    method: 'GET',
  },
  'log-viewer.hosts': {
    name: 'log-viewer.hosts',
    path: '/log-viewer/api/hosts',
    params: undefined,
    method: 'GET',
  },
  'log-viewer.folders': {
    name: 'log-viewer.folders',
    path: '/log-viewer/api/folders',
    params: undefined,
    method: 'GET',
  },
  'log-viewer.folders.download': {
    name: 'log-viewer.folders.download',
    path: '/log-viewer/api/folders/{folderIdentifier}/download',
    params: {
      folderIdentifier: 'string',
    },
    method: 'GET',
  },
  'log-viewer.folders.clear-cache': {
    name: 'log-viewer.folders.clear-cache',
    path: '/log-viewer/api/folders/{folderIdentifier}/clear-cache',
    params: {
      folderIdentifier: 'string',
    },
    method: 'POST',
  },
  'log-viewer.folders.delete': {
    name: 'log-viewer.folders.delete',
    path: '/log-viewer/api/folders/{folderIdentifier}',
    params: {
      folderIdentifier: 'string',
    },
    method: 'DELETE',
  },
  'log-viewer.files': {
    name: 'log-viewer.files',
    path: '/log-viewer/api/files',
    params: undefined,
    method: 'GET',
  },
  'log-viewer.files.download': {
    name: 'log-viewer.files.download',
    path: '/log-viewer/api/files/{fileIdentifier}/download',
    params: {
      fileIdentifier: 'string',
    },
    method: 'GET',
  },
  'log-viewer.files.clear-cache': {
    name: 'log-viewer.files.clear-cache',
    path: '/log-viewer/api/files/{fileIdentifier}/clear-cache',
    params: {
      fileIdentifier: 'string',
    },
    method: 'POST',
  },
  'log-viewer.files.delete': {
    name: 'log-viewer.files.delete',
    path: '/log-viewer/api/files/{fileIdentifier}',
    params: {
      fileIdentifier: 'string',
    },
    method: 'DELETE',
  },
  'log-viewer.files.clear-cache-all': {
    name: 'log-viewer.files.clear-cache-all',
    path: '/log-viewer/api/clear-cache-all',
    params: undefined,
    method: 'POST',
  },
  'log-viewer.files.delete-multiple-files': {
    name: 'log-viewer.files.delete-multiple-files',
    path: '/log-viewer/api/delete-multiple-files',
    params: undefined,
    method: 'POST',
  },
  'log-viewer.logs': {
    name: 'log-viewer.logs',
    path: '/log-viewer/api/logs',
    params: undefined,
    method: 'GET',
  },
  'log-viewer.index': {
    name: 'log-viewer.index',
    path: '/log-viewer/{view?}',
    params: {
      view: 'string',
    },
    method: 'GET',
  },
  '/': {
    name: '/',
    path: '/',
    params: undefined,
    method: 'GET',
  },
  'dashboard': {
    name: 'dashboard',
    path: '/dashboard',
    params: undefined,
    method: 'GET',
  },
}

declare global {
  interface Window {
    Routes: Record<App.Route.Name, App.Route.Entity>
  }
}

if (typeof window !== undefined && typeof window.Routes !== undefined)
  window.Routes = Routes

export { Routes }
