// This file is auto generated by TypescriptableLaravel.
declare namespace App {
  declare namespace Route {
    export type NamePath = 'login' | 'logout' | 'password.email' | 'password.reset' | 'password.update' | 'register' | 'user-profile-information.update' | 'user-password.update' | 'password.confirm' | 'password.confirmation' | 'two-factor-challenge' | 'two-factor.disable' | 'two-factor.confirm' | 'two-factor.qr-code' | 'two-factor.secret-key' | 'user/two-factor-recovery-codes' | 'profile.show' | 'other-browser-sessions.destroy' | 'current-user-photo.destroy' | 'current-user.destroy' | 'sanctum.csrf-cookie' | 'log-viewer.hosts' | 'log-viewer.folders' | 'log-viewer.folders.download' | 'log-viewer.folders.clear-cache' | 'log-viewer.folders.delete' | 'log-viewer.files' | 'log-viewer.files.download' | 'log-viewer.files.clear-cache' | 'log-viewer.files.delete' | 'log-viewer.files.clear-cache-all' | 'log-viewer.files.delete-multiple-files' | 'log-viewer.logs' | 'log-viewer.index' | '/' | 'dashboard'
    export type Name = 'login' | 'logout' | 'password.email' | 'password.reset' | 'password.update' | 'register' | 'user-profile-information.update' | 'user-password.update' | 'password.confirm' | 'password.confirmation' | 'two-factor-challenge' | 'two-factor.disable' | 'two-factor.confirm' | 'two-factor.qr-code' | 'two-factor.secret-key' | 'user/two-factor-recovery-codes' | 'profile.show' | 'other-browser-sessions.destroy' | 'current-user-photo.destroy' | 'current-user.destroy' | 'sanctum.csrf-cookie' | 'log-viewer.hosts' | 'log-viewer.folders' | 'log-viewer.folders.download' | 'log-viewer.folders.clear-cache' | 'log-viewer.folders.delete' | 'log-viewer.files' | 'log-viewer.files.download' | 'log-viewer.files.clear-cache' | 'log-viewer.files.delete' | 'log-viewer.files.clear-cache-all' | 'log-viewer.files.delete-multiple-files' | 'log-viewer.logs' | 'log-viewer.index' | '/' | 'dashboard'
    export type Path = '/login' | '/logout' | '/forgot-password' | '/reset-password/{token}' | '/reset-password' | '/register' | '/user/profile-information' | '/user/password' | '/user/confirm-password' | '/user/confirmed-password-status' | '/two-factor-challenge' | '/user/two-factor-authentication' | '/user/confirmed-two-factor-authentication' | '/user/two-factor-qr-code' | '/user/two-factor-secret-key' | '/user/two-factor-recovery-codes' | '/user/profile' | '/user/other-browser-sessions' | '/user/profile-photo' | '/user' | '/sanctum/csrf-cookie' | '/log-viewer/api/hosts' | '/log-viewer/api/folders' | '/log-viewer/api/folders/{folderIdentifier}/download' | '/log-viewer/api/folders/{folderIdentifier}/clear-cache' | '/log-viewer/api/folders/{folderIdentifier}' | '/log-viewer/api/files' | '/log-viewer/api/files/{fileIdentifier}/download' | '/log-viewer/api/files/{fileIdentifier}/clear-cache' | '/log-viewer/api/files/{fileIdentifier}' | '/log-viewer/api/clear-cache-all' | '/log-viewer/api/delete-multiple-files' | '/log-viewer/api/logs' | '/log-viewer/{view?}' | '/' | '/dashboard';
    export type Params = {
      'login': never,
      'logout': never,
      'password.email': never,
      'password.reset': {
        'token'?: Route.Param
      },
      'password.update': never,
      'register': never,
      'user-profile-information.update': never,
      'user-password.update': never,
      'password.confirm': never,
      'password.confirmation': never,
      'two-factor-challenge': never,
      'two-factor.disable': never,
      'two-factor.confirm': never,
      'two-factor.qr-code': never,
      'two-factor.secret-key': never,
      'user/two-factor-recovery-codes': never,
      'profile.show': never,
      'other-browser-sessions.destroy': never,
      'current-user-photo.destroy': never,
      'current-user.destroy': never,
      'sanctum.csrf-cookie': never,
      'log-viewer.hosts': never,
      'log-viewer.folders': never,
      'log-viewer.folders.download': {
        'folderIdentifier'?: Route.Param
      },
      'log-viewer.folders.clear-cache': {
        'folderIdentifier'?: Route.Param
      },
      'log-viewer.folders.delete': {
        'folderIdentifier'?: Route.Param
      },
      'log-viewer.files': never,
      'log-viewer.files.download': {
        'fileIdentifier'?: Route.Param
      },
      'log-viewer.files.clear-cache': {
        'fileIdentifier'?: Route.Param
      },
      'log-viewer.files.delete': {
        'fileIdentifier'?: Route.Param
      },
      'log-viewer.files.clear-cache-all': never,
      'log-viewer.files.delete-multiple-files': never,
      'log-viewer.logs': never,
      'log-viewer.index': {
        'view'?: Route.Param
      },
      '/': never,
      'dashboard': never
    };

    export type Method = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
    export interface Entity { name: Route.Name; path: Route.Path; params?: Route.Params[Route.Name],  method: Route.Method; }

    declare namespace Typed {
      type LoginPOST = {
        name: 'login',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogoutPOST = {
        name: 'logout',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type ForgotPasswordPOST = {
        name: 'password.email',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type ResetPasswordTokenGET = {
        name: 'password.reset',
        params: {
          token: Route.Param,
        },
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type ResetPasswordPOST = {
        name: 'password.update',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type RegisterPOST = {
        name: 'register',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type UserProfileInformationPUT = {
        name: 'user-profile-information.update',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type UserPasswordPUT = {
        name: 'user-password.update',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type UserConfirmPasswordPOST = {
        name: 'password.confirm',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type UserConfirmedPasswordStatusGET = {
        name: 'password.confirmation',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type TwoFactorChallengePOST = {
        name: 'two-factor-challenge',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type UserTwoFactorAuthenticationDELETE = {
        name: 'two-factor.disable',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type UserConfirmedTwoFactorAuthenticationPOST = {
        name: 'two-factor.confirm',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type UserTwoFactorQrCodeGET = {
        name: 'two-factor.qr-code',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type UserTwoFactorSecretKeyGET = {
        name: 'two-factor.secret-key',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type UserTwoFactorRecoveryCodesPOST = {
        name: 'user/two-factor-recovery-codes',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type UserProfileGET = {
        name: 'profile.show',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type UserOtherBrowserSessionsDELETE = {
        name: 'other-browser-sessions.destroy',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type UserProfilePhotoDELETE = {
        name: 'current-user-photo.destroy',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type UserDELETE = {
        name: 'current-user.destroy',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type SanctumCsrfCookieGET = {
        name: 'sanctum.csrf-cookie',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogViewerApiHostsGET = {
        name: 'log-viewer.hosts',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogViewerApiFoldersGET = {
        name: 'log-viewer.folders',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogViewerApiFoldersFolderIdentifierDownloadGET = {
        name: 'log-viewer.folders.download',
        params: {
          folderIdentifier: Route.Param,
        },
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogViewerApiFoldersFolderIdentifierClearCachePOST = {
        name: 'log-viewer.folders.clear-cache',
        params: {
          folderIdentifier: Route.Param,
        },
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogViewerApiFoldersFolderIdentifierDELETE = {
        name: 'log-viewer.folders.delete',
        params: {
          folderIdentifier: Route.Param,
        },
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogViewerApiFilesGET = {
        name: 'log-viewer.files',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogViewerApiFilesFileIdentifierDownloadGET = {
        name: 'log-viewer.files.download',
        params: {
          fileIdentifier: Route.Param,
        },
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogViewerApiFilesFileIdentifierClearCachePOST = {
        name: 'log-viewer.files.clear-cache',
        params: {
          fileIdentifier: Route.Param,
        },
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogViewerApiFilesFileIdentifierDELETE = {
        name: 'log-viewer.files.delete',
        params: {
          fileIdentifier: Route.Param,
        },
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogViewerApiClearCacheAllPOST = {
        name: 'log-viewer.files.clear-cache-all',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogViewerApiDeleteMultipleFilesPOST = {
        name: 'log-viewer.files.delete-multiple-files',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogViewerApiLogsGET = {
        name: 'log-viewer.logs',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type LogViewerViewGET = {
        name: 'log-viewer.index',
        params: {
          view?: Route.Param,
        },
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type GET = {
        name: '/',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      };
      type DashboardGET = {
        name: 'dashboard',
        params?: undefined,
        query?: Record<string, Route.Param>,
        hash?: string,
      }
    }
    export type Param = string | number | boolean | undefined
    export type Type = Route.Typed.LoginPOST | Route.Typed.LogoutPOST | Route.Typed.ForgotPasswordPOST | Route.Typed.ResetPasswordTokenGET | Route.Typed.ResetPasswordPOST | Route.Typed.RegisterPOST | Route.Typed.UserProfileInformationPUT | Route.Typed.UserPasswordPUT | Route.Typed.UserConfirmPasswordPOST | Route.Typed.UserConfirmedPasswordStatusGET | Route.Typed.TwoFactorChallengePOST | Route.Typed.UserTwoFactorAuthenticationDELETE | Route.Typed.UserConfirmedTwoFactorAuthenticationPOST | Route.Typed.UserTwoFactorQrCodeGET | Route.Typed.UserTwoFactorSecretKeyGET | Route.Typed.UserTwoFactorRecoveryCodesPOST | Route.Typed.UserProfileGET | Route.Typed.UserOtherBrowserSessionsDELETE | Route.Typed.UserProfilePhotoDELETE | Route.Typed.UserDELETE | Route.Typed.SanctumCsrfCookieGET | Route.Typed.LogViewerApiHostsGET | Route.Typed.LogViewerApiFoldersGET | Route.Typed.LogViewerApiFoldersFolderIdentifierDownloadGET | Route.Typed.LogViewerApiFoldersFolderIdentifierClearCachePOST | Route.Typed.LogViewerApiFoldersFolderIdentifierDELETE | Route.Typed.LogViewerApiFilesGET | Route.Typed.LogViewerApiFilesFileIdentifierDownloadGET | Route.Typed.LogViewerApiFilesFileIdentifierClearCachePOST | Route.Typed.LogViewerApiFilesFileIdentifierDELETE | Route.Typed.LogViewerApiClearCacheAllPOST | Route.Typed.LogViewerApiDeleteMultipleFilesPOST | Route.Typed.LogViewerApiLogsGET | Route.Typed.LogViewerViewGET | Route.Typed.GET | Route.Typed.DashboardGET
    export type TypeGet = Route.Typed.ResetPasswordTokenGET | Route.Typed.UserConfirmedPasswordStatusGET | Route.Typed.UserTwoFactorQrCodeGET | Route.Typed.UserTwoFactorSecretKeyGET | Route.Typed.UserProfileGET | Route.Typed.SanctumCsrfCookieGET | Route.Typed.LogViewerApiHostsGET | Route.Typed.LogViewerApiFoldersGET | Route.Typed.LogViewerApiFoldersFolderIdentifierDownloadGET | Route.Typed.LogViewerApiFilesGET | Route.Typed.LogViewerApiFilesFileIdentifierDownloadGET | Route.Typed.LogViewerApiLogsGET | Route.Typed.LogViewerViewGET | Route.Typed.GET | Route.Typed.DashboardGET
    export type TypePost = Route.Typed.LoginPOST | Route.Typed.LogoutPOST | Route.Typed.ForgotPasswordPOST | Route.Typed.ResetPasswordPOST | Route.Typed.RegisterPOST | Route.Typed.UserConfirmPasswordPOST | Route.Typed.TwoFactorChallengePOST | Route.Typed.UserConfirmedTwoFactorAuthenticationPOST | Route.Typed.UserTwoFactorRecoveryCodesPOST | Route.Typed.LogViewerApiFoldersFolderIdentifierClearCachePOST | Route.Typed.LogViewerApiFilesFileIdentifierClearCachePOST | Route.Typed.LogViewerApiClearCacheAllPOST | Route.Typed.LogViewerApiDeleteMultipleFilesPOST
    export type TypePut = Route.Typed.UserProfileInformationPUT | Route.Typed.UserPasswordPUT
    export type TypePatch = 
    export type TypeDelete = Route.Typed.UserTwoFactorAuthenticationDELETE | Route.Typed.UserOtherBrowserSessionsDELETE | Route.Typed.UserProfilePhotoDELETE | Route.Typed.UserDELETE | Route.Typed.LogViewerApiFoldersFolderIdentifierDELETE | Route.Typed.LogViewerApiFilesFileIdentifierDELETE
  }
}